[package]
name = "SATAN"
version = "0.1.0"
authors = ["Mariana Meireles <mariana@psychonautgirl.space>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
